"""mission 6: capability engine, subscriptions, billing, gifted v2, bundles, service auth, outbox

Revision ID: 4a35a2c457fb
Revises: f006149cdf49
Create Date: 2026-09-14 02:09:40.473225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.sa_types


# revision identifiers, used by Alembic.
revision: str = '4a35a2c457fb'
down_revision: Union[str, None] = 'f006149cdf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_webhook_events',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('received_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('processed_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_billing_webhook_event')
    )
    op.create_table('bundles',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundles_slug'), 'bundles', ['slug'], unique=True)
    op.create_table('entitlement_definitions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'key', name='uq_entitlement_definition_product_key')
    )
    op.create_index(op.f('ix_entitlement_definitions_product_id'), 'entitlement_definitions', ['product_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_customer_ref', sa.String(length=200), nullable=False),
    sa.Column('provider_subscription_ref', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subscription_ref', name='uq_subscription_provider_ref')
    )
    op.create_index(op.f('ix_subscriptions_product_id'), 'subscriptions', ['product_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('bundle_access',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('bundle_id', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('subscription_id', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_access_bundle_id'), 'bundle_access', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_bundle_access_user_id'), 'bundle_access', ['user_id'], unique=False)
    op.create_table('bundle_product_plans',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('bundle_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_id', 'product_id', name='uq_bundle_product')
    )
    op.create_index(op.f('ix_bundle_product_plans_bundle_id'), 'bundle_product_plans', ['bundle_id'], unique=False)
    op.create_table('gifted_access',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('granted_by', sa.String(length=48), nullable=False),
    sa.Column('granted_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('starts_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revoked_by', sa.String(length=48), nullable=True),
    sa.Column('revoked_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gifted_access_product_id'), 'gifted_access', ['product_id'], unique=False)
    op.create_index(op.f('ix_gifted_access_user_id'), 'gifted_access', ['user_id'], unique=False)
    op.create_table('plan_entitlements',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.Column('entitlement_definition_id', sa.String(length=48), nullable=False),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_string', sa.String(length=120), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_definition_id'], ['entitlement_definitions.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'entitlement_definition_id', name='uq_plan_entitlement')
    )
    op.create_index(op.f('ix_plan_entitlements_entitlement_definition_id'), 'plan_entitlements', ['entitlement_definition_id'], unique=False)
    op.create_index(op.f('ix_plan_entitlements_plan_id'), 'plan_entitlements', ['plan_id'], unique=False)
    op.create_table('service_grants',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('client_id', sa.String(length=60), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'scope', name='uq_service_grant')
    )
    op.create_index(op.f('ix_service_grants_client_id'), 'service_grants', ['client_id'], unique=False)
    op.create_table('subscription_items',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('subscription_id', sa.String(length=48), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_items_subscription_id'), 'subscription_items', ['subscription_id'], unique=False)
    # batch_alter_table (not plain op.add_column/op.create_foreign_key):
    # SQLite cannot ALTER a table to add a foreign key constraint directly
    # (only a full copy-and-move rebuild, which batch mode performs for
    # us) - on PostgreSQL, batch mode transparently falls back to plain
    # ALTER statements, so this is the portable form for both targets
    # (mission-brief Phase 46: this migration must work against SQLite
    # dev and a real Postgres deployment).
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('webhook_signing_secret', sa.String(length=128), nullable=True))

    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('tax_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fee_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('net_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refunded_amount_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occurred_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(
            'fk_payment_records_subscription_id', 'subscriptions', ['subscription_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_records_subscription_id', type_='foreignkey')
        batch_op.drop_column('occurred_at')
        batch_op.drop_column('refunded_amount_cents')
        batch_op.drop_column('net_cents')
        batch_op.drop_column('fee_cents')
        batch_op.drop_column('tax_cents')
        batch_op.drop_column('subscription_id')

    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.drop_column('webhook_signing_secret')
        batch_op.drop_column('webhook_url')
    op.drop_index(op.f('ix_subscription_items_subscription_id'), table_name='subscription_items')
    op.drop_table('subscription_items')
    op.drop_index(op.f('ix_service_grants_client_id'), table_name='service_grants')
    op.drop_table('service_grants')
    op.drop_index(op.f('ix_plan_entitlements_plan_id'), table_name='plan_entitlements')
    op.drop_index(op.f('ix_plan_entitlements_entitlement_definition_id'), table_name='plan_entitlements')
    op.drop_table('plan_entitlements')
    op.drop_index(op.f('ix_gifted_access_user_id'), table_name='gifted_access')
    op.drop_index(op.f('ix_gifted_access_product_id'), table_name='gifted_access')
    op.drop_table('gifted_access')
    op.drop_index(op.f('ix_bundle_product_plans_bundle_id'), table_name='bundle_product_plans')
    op.drop_table('bundle_product_plans')
    op.drop_index(op.f('ix_bundle_access_user_id'), table_name='bundle_access')
    op.drop_index(op.f('ix_bundle_access_bundle_id'), table_name='bundle_access')
    op.drop_table('bundle_access')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_product_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_entitlement_definitions_product_id'), table_name='entitlement_definitions')
    op.drop_table('entitlement_definitions')
    op.drop_index(op.f('ix_bundles_slug'), table_name='bundles')
    op.drop_table('bundles')
    op.drop_table('billing_webhook_events')
    # ### end Alembic commands ###
