"""mission 6 continuation: verified email change flow

Revision ID: 76e4bdbdea17
Revises: 8e2a4ae9d31e
Create Date: 2026-09-14 04:16:20.405410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.sa_types


# revision identifiers, used by Alembic.
revision: str = '76e4bdbdea17'
down_revision: Union[str, None] = '8e2a4ae9d31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_tokens',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('new_email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_change_tokens_token_hash'), 'email_change_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_change_tokens_user_id'), 'email_change_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('pending_new_email', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_new_email')
    op.drop_index(op.f('ix_email_change_tokens_user_id'), table_name='email_change_tokens')
    op.drop_index(op.f('ix_email_change_tokens_token_hash'), table_name='email_change_tokens')
    op.drop_table('email_change_tokens')
    # ### end Alembic commands ###
