"""mission 6 continuation: product subscription manager (plan catalog, versioning, prices, promotions, account closure, encrypted webhook secret)

Revision ID: 8e2a4ae9d31e
Revises: e76146991275
Create Date: 2026-09-14 03:26:06.663751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.sa_types


# revision identifiers, used by Alembic.
revision: str = '8e2a4ae9d31e'
down_revision: Union[str, None] = 'e76146991275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_closure_requests',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('requested_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_closure_requests_user_id'), 'account_closure_requests', ['user_id'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('capability_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=48), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('published_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version_number', name='uq_plan_version_number')
    )
    op.create_index(op.f('ix_plan_versions_plan_id'), 'plan_versions', ['plan_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.Column('plan_version_id', sa.String(length=48), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_price_id', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('retired_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_plan_id'), 'prices', ['plan_id'], unique=False)
    op.create_index(op.f('ix_prices_product_id'), 'prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_prices_provider_price_id'), 'prices', ['provider_price_id'], unique=False)
    op.create_table('promotion_access',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.Column('plan_version_id', sa.String(length=48), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source_code', sa.String(length=80), nullable=True),
    sa.Column('granted_by', sa.String(length=48), nullable=True),
    sa.Column('starts_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_access_product_id'), 'promotion_access', ['product_id'], unique=False)
    op.create_index(op.f('ix_promotion_access_user_id'), 'promotion_access', ['user_id'], unique=False)

    # batch_alter_table throughout below: portable SQLite/Postgres form
    # (SQLite cannot ALTER-ADD a foreign key directly), and every new
    # NOT NULL column gets a server_default so this migration applies
    # cleanly against a POPULATED V1/V2 table (mission-brief Phase 46) -
    # the default is dropped again immediately after backfill so the
    # column's long-term definition matches the ORM model exactly.
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_version_id', sa.String(length=48), nullable=True))

    with op.batch_alter_table('gifted_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_version_id', sa.String(length=48), nullable=True))

    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_signing_secret_encrypted', sa.String(length=400), nullable=True))
        # The old plaintext column's data is intentionally NOT migrated
        # forward - no real webhook secret exists in any pre-production
        # deployment of this schema yet (see MISSION_6_SECURITY_REVIEW.md
        # continuation); any client that had configured a webhook before
        # this migration must re-run `configure_webhook` afterward.
        batch_op.drop_column('webhook_signing_secret')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('upgrade_rank', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('gifted_eligible', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('trial_eligible', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('current_version_id', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column(
            'updated_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ))
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('status', server_default=None)
        batch_op.alter_column('is_public', server_default=None)
        batch_op.alter_column('sort_order', server_default=None)
        batch_op.alter_column('upgrade_rank', server_default=None)
        batch_op.alter_column('gifted_eligible', server_default=None)
        batch_op.alter_column('trial_eligible', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('plan_version_id', sa.String(length=48), nullable=True))
        batch_op.create_foreign_key('fk_subscriptions_price_id', 'prices', ['price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriptions_price_id', type_='foreignkey')
        batch_op.drop_column('plan_version_id')
        batch_op.drop_column('price_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('current_version_id')
        batch_op.drop_column('trial_eligible')
        batch_op.drop_column('gifted_eligible')
        batch_op.drop_column('upgrade_rank')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_public')
        batch_op.drop_column('status')
        batch_op.drop_column('description')

    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_signing_secret', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('webhook_signing_secret_encrypted')

    with op.batch_alter_table('gifted_access', schema=None) as batch_op:
        batch_op.drop_column('plan_version_id')

    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.drop_column('plan_version_id')
    op.drop_index(op.f('ix_promotion_access_user_id'), table_name='promotion_access')
    op.drop_index(op.f('ix_promotion_access_product_id'), table_name='promotion_access')
    op.drop_table('promotion_access')
    op.drop_index(op.f('ix_prices_provider_price_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_product_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_plan_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_plan_versions_plan_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_account_closure_requests_user_id'), table_name='account_closure_requests')
    op.drop_table('account_closure_requests')
    # ### end Alembic commands ###
