"""create platform core tables

Revision ID: f006149cdf49
Revises: 
Create Date: 2026-09-13 14:03:17.799999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.sa_types


# revision identifiers, used by Alembic.
revision: str = 'f006149cdf49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('icon_ref', sa.String(length=80), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('actor_user_id', sa.String(length=48), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=48), nullable=True),
    sa.Column('product_id', sa.String(length=40), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=60), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=True),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_user_id'), 'payment_records', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'slug', name='uq_plan_product_slug')
    )
    op.create_index(op.f('ix_plans_product_id'), 'plans', ['product_id'], unique=False)
    op.create_table('product_memberships',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_membership_user_product')
    )
    op.create_index(op.f('ix_product_memberships_product_id'), 'product_memberships', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_memberships_user_id'), 'product_memberships', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('role_slug', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('granted_by', sa.String(length=48), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_slug'], ['roles.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_slug', 'scope', name='uq_role_assignment')
    )
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_table('authorization_codes',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=500), nullable=True),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_codes_code_hash'), 'authorization_codes', ['code_hash'], unique=True)
    op.create_table('entitlements',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.String(length=48), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entitlements_product_id'), 'entitlements', ['product_id'], unique=False)
    op.create_index(op.f('ix_entitlements_user_id'), 'entitlements', ['user_id'], unique=False)
    op.create_table('oauth_refresh_tokens',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('expires_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_refresh_tokens_token_hash'), 'oauth_refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_refresh_tokens_token_hash'), table_name='oauth_refresh_tokens')
    op.drop_table('oauth_refresh_tokens')
    op.drop_index(op.f('ix_entitlements_user_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_product_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_authorization_codes_code_hash'), table_name='authorization_codes')
    op.drop_table('authorization_codes')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_product_memberships_user_id'), table_name='product_memberships')
    op.drop_index(op.f('ix_product_memberships_product_id'), table_name='product_memberships')
    op.drop_table('product_memberships')
    op.drop_index(op.f('ix_plans_product_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_payment_records_user_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('products')
    # ### end Alembic commands ###
