"""add per-user download preferences

Revision ID: 2b437cf7ea5c
Revises: 20491e9286b1
Create Date: 2026-09-04 18:34:16.475861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.sa_types


# revision identifiers, used by Alembic.
revision: str = '2b437cf7ea5c'
down_revision: Union[str, None] = '20491e9286b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_download_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('container_mode', sa.String(length=20), nullable=False),
    sa.Column('cookie_source', sa.String(length=20), nullable=False),
    sa.Column('cookie_file_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.sa_types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_download_preferences')
    # ### end Alembic commands ###
